// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpNlz7WWyer4Vs-FX5ImNVYSDPFw3Xr00',
    appId: '1:1010647103548:web:9d52f554ab71bc5132ab39',
    messagingSenderId: '1010647103548',
    projectId: 'intolergy',
    authDomain: 'intolergy.firebaseapp.com',
    storageBucket: 'intolergy.appspot.com',
    measurementId: 'G-ZYTF2LSP93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTxEwv9uYBpZNXqLgQUFmEgqyAI2axA3Q',
    appId: '1:1010647103548:android:dc790bcc7d0669ec32ab39',
    messagingSenderId: '1010647103548',
    projectId: 'intolergy',
    storageBucket: 'intolergy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBCis_OzJ9FdF9LsHaPkdP9fpFZs8IP7o',
    appId: '1:1010647103548:ios:9ed0422e95a5ba3132ab39',
    messagingSenderId: '1010647103548',
    projectId: 'intolergy',
    storageBucket: 'intolergy.appspot.com',
    iosClientId: '1010647103548-qs49e1ad2q13sr3n6vupkaulch1938cj.apps.googleusercontent.com',
    iosBundleId: 'com.example.intolergy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBCis_OzJ9FdF9LsHaPkdP9fpFZs8IP7o',
    appId: '1:1010647103548:ios:ed20ab9148610f4f32ab39',
    messagingSenderId: '1010647103548',
    projectId: 'intolergy',
    storageBucket: 'intolergy.appspot.com',
    iosClientId: '1010647103548-csb061c2po915kcrl03injvgdkp1kvc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.intolergy.RunnerTests',
  );
}
